export const departmentOptions = [
  { value: "D1", label: "D1" },
  { value: "D2", label: "D2" },
  { value: "D3", label: "D3" },
  { value: "D4", label: "D4" },
  { value: "D5", label: "D5" },
  { value: "D6", label: "D6" },
  { value: "D7", label: "D7" },
  { value: "D8", label: "D8" },
  { value: "D9", label: "D9" },
  { value: "D10", label: "D10" },
  { value: "D11", label: "D11" },
  { value: "D12", label: "D12" },
  { value: "D13", label: "D13" },
  { value: "L1", label: "L1" },
  { value: "L2", label: "L2" },
  { value: "L3", label: "L3" },
  { value: "L4", label: "L4" },
  { value: "L5", label: "L5" },
  { value: "L6", label: "L6" },
  { value: "L7", label: "L7" },
  { value: "L8", label: "L8" },
  { value: "L9", label: "L9" },
];